### ISSUE TITLE
Document re-ingestion of data in pipeline

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#134]
Checklist:

* [x] Verify that re-ingestion and reprocessing work as expected
* ~[ ] document the procedure at HOWTO level~
* [x] document unexpected side-effects (there are some)

**Comment by darkk** [comment]
I believe that #183 mostly addresses the issue. Unfortunately it's not a HOWTO-level, but checklist-level due to unclear ways to predict pathological performance.

**Comment by hellais** [comment]
@darkk there are some pending comments on that PR that I would like to have at least be addressed before this is considered closed.

**Comment by hellais** [comment]
@darkk can you speak about the "unexpected side-effects (there are some)" of reprocessing the measurements?

**Comment by darkk** [comment]
Some are described in [Preface section of the doc](https://github.com/ooni/pipeline/blob/dbd4ea463efc2137490e18812185b0a7849712b0/docs/reprocess-report.md#preface). I've mainly meant that blunt reprocessing of all the tables would produce lots of unnecessary updates to PG database, so, `code_ver` and `min_compat_code_ver` are introduced.
I've also meant that following _fast path_ and updating measurement flags using the features manually may lead to inconsistencies, so it should be done in-sync with code. You've also seen that during #151, that's why #162 appeared.
That's mostly it :-)

**Comment by hellais** [comment]
As we the howto level tutorial was placed out of scope I think we can consider this issue solved.
