### ISSUE TITLE
Access denied on some files

### ISSUE THREAD

**Issue by fortuna** [ooni/pipeline#72]
I've found a number of files in OONI that I don't have access to.

For example:
```
curl -I https://s3.amazonaws.com/ooni-public/sanitised/2016-04-22/20160421T054046Z-GB-AS21260-tcp_connect-HMHEzish2yMQ04XuDzGb2sjfZlfcZ26jLWxxuMMSoO17b3Dqee5jvgquDZAUma0h-0.1.0-probe.json
HTTP/1.1 403 Forbidden
x-amz-request-id: FA7AD6D9C27B6B53
x-amz-id-2: ihKnRZAc8jG/D8Qz6cLlAjSED2DHjbeROu7putSh9oOwMHyOcU6U9M1E4QNcKcfaYHf1pJr2AY4=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Sat, 05 Aug 2017 03:41:58 GMT
Server: AmazonS3
```

Another example: https://s3.amazonaws.com/ooni-public/sanitised/2016-04-22/20160421T054417Z-GB-AS21260-tcp_connect-hgLV2wZB9NaOWWtbO3gPth0bzy3kJabXjLdn3iPJEtc59KTJeXkfqg2uQtgaiIRS-0.1.0-probe.json

I can't find them again by querying the files API anymore, but I think they may be on some random page (see issue https://github.com/TheTorProject/ooni-pipeline/issues/73)

Any idea what's going on?

**Comment by fortuna** [comment]
FYI, I see the same issue on the file listing on the website:
https://measurements.ooni.torproject.org/files/by_date/2016-04-11

Many links for AS5607 GB are busted.

This is part of a date range that has an unusually high number of reports, which is another sign that something may be wrong with the pipeline:

![image](https://user-images.githubusercontent.com/113565/29030966-bd1b94ce-7b5a-11e7-805a-1b0bc689b876.png)

**Comment by hellais** [comment]
I have looked into it and it appears that there is no file `ooni-public/sanitised/2016-04-22/20160421T054046Z-GB-AS21260-tcp_connect-HMHEzish2yMQ04XuDzGb2sjfZlfcZ26jLWxxuMMSoO17b3Dqee5jvgquDZAUma0h-0.1.0-probe.json` on s3.

I do see however the measurement listed inside of the new beta measurements API here: https://measurements-beta.ooni.io/files/by_date/2016-04-21.

I believe this is due to the fact that our "legacy" pipeline is configured to not process those particular reports (see: https://lists.torproject.org/pipermail/ooni-operators/2016-June/000003.html), since it was spamming our pipeline, while the new pipeline can ingest them just fine.

As a result the sanitised version is not being generated and uploaded to s3.

I would not consider this a big issues as those reports are just from a single vantage point and you can probably safely ignore them.

**Comment by darkk** [comment]
Both `2016-04-22/20160421T054417Z-GB-AS21260-tcp_connect-hgLV2wZB9NaOWWtbO3gPth0bzy3kJabXjLdn3iPJEtc59KTJeXkfqg2uQtgaiIRS-0.1.0-probe.json` and `2016-04-22/20160421T054046Z-GB-AS21260-tcp_connect-HMHEzish2yMQ04XuDzGb2sjfZlfcZ26jLWxxuMMSoO17b3Dqee5jvgquDZAUma0h-0.1.0-probe.json` are accessible as `https://api.ooni.io/files/download/....yaml`
E.g. `https://api.ooni.io/files/download/2016-04-22/20160421T054046Z-GB-AS21260-tcp_connect-HMHEzish2yMQ04XuDzGb2sjfZlfcZ26jLWxxuMMSoO17b3Dqee5jvgquDZAUma0h-0.1.0-probe.yaml`

The new pipeline does not mangle filename and keeps `.yaml` files named as `.yaml` files even while it converts it to json. The filename is part of PK to identify the measurement, so extension is preserved. I believe it was another source of confusion.

I don't know if API should mangle filename and issue a redirect for *.yaml files to preserve old links or not. It's a ticket for ooni/api if it should.

Probably, this ticket can be closed.
