### ISSUE TITLE
Out-of-place entries

### ISSUE THREAD

**Issue by fortuna** [ooni/pipeline#73]
There's something wrong with the files API.

If you query for:
https://measurements.ooni.torproject.org/api/v1/files?since=2012-01-01&until=2012-12-31&limit=1000

You will find this out-of-place entry on a `2017-03-11` directory:
```
{
  "download_url": "https://s3.amazonaws.com/ooni-public/sanitised/2017-03-11/20120101T000204Z-ZZ-AS0-ndt-20170310T200609Z_AS0_e0fMUvaPSVMVAiKQkwpApLho6yot0OfzbiQUydLM5SR8ywu1Ff-0.2.0-probe.json",
  "index": 342379,
  "probe_asn": "AS0",
  "probe_cc": "ZZ",
  "test_start_time": "2012-01-01T00:02:04Z"
},
```

Any idea what's going on?

**Comment by hellais** [comment]
I think the reason why you find this unexpected is that there is that the directories where reports are put into is a bit confusing.

The date for the directory were reports are put into is not actually related to when the measurement was **run**, but is rather the timestamp for bucket when the measurements were **processed**.
What this means in practice is that if I run a measurement today (2017-08-16), but upload it to the OONI collector in 10 days, it will actually end up inside of the bucket 2017-08-26, not 2017-08-16, since that is when it is processed.

To get back to this specific measurements, that is likely a bug in the clock of the person running the measurement (or maybe a measurement-kit bug that was not reporting the date correctly).

We actually "trust" the probe to set a timestamp (and I don't know of any other better way of doing this), which means that if the users clock is off, we will take it for what it is.

I believe we do have some logic in place to detect clearly faulty measurements, that have inconsistent timing and bring them back to unix epoch, but maybe this was an edge case that we didn't detect for some reason.
