### ISSUE TITLE
Add support for extracting useful "anomaly" information from measurements

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#76]
As discussed with @darkk and outlined in other tickets (such as: https://github.com/TheTorProject/ooni-measurements/issues/32), we need to extract some useful information from measurements and present it to end users (via measurement API and the like).

The sorts of information that should be extracted and exposed includes:

* `failure` a boolean value that is going to be true if the pipeline side analysis failed for a variety of reasons, that can include, but is not limited to:
  * The control measurement failed, so it's not possible to determine if blocking happened
  * The measurement is malformed (some keys are missing, some are extra etc.)
  * There was some bug in some part of the code

* `anomaly` a boolean value used to identify measurements that "smell like network interference". In the case of Web Connectivity this can mean that the body length doesn't match the expected value, the headers are inconsistent, the DNS lookup is inconsistent, etc. In HTTP Header Field Manipulation it means that the response we got are inconsistent, though we didn't necessarily see a known vendor fingerprint (if we do see it anomaly should still be true), etc.

* `confirmed` a boolean value that we use to annotate reports that we are 100% sure are an instance of "network interference" (censorship, middle box, etc.) This can be in the case of web connectivity that we found a known blockpage fingerprint or the IP in the DNS resolution is know to be that of a censor. In the case of HTTP Invalid Request Line or Header Field Manipulation when we see the fingerprint of a known middlebox. For the apps this is simply if the heuristics used to assess if the app is blocked said that was the case.

This high level boolean (`confirmed`) could maybe be "enriched" with a separate `enum` type that mentions what is the exact reason for it being `confirmed`. For example: `blockpage found` (maybe also the ID of the blockpage), `dns-inconsistent` (maybe with the inconsistent DNS too), etc. We may also want to have on top of this what is the "reason for censorship", that can be a fine grained type that as @darkk wrote here: https://github.com/TheTorProject/ooni-measurements/issues/32#issuecomment-327276050.

The measurements that "normal", as in they don't present any indication of censorship happening, should be identified by simply checking for all the keys being false.

Other things that we care to extract while we are at it that are test specific:

For the web_connectivity test:

* If the response is that of a known CDN (ex. "Cloudflare wants you to fill out this captcha", "Google: People from your country are not welcome to use our services", etc.)

This gist may be useful to extract some of these values: https://gist.github.com/hellais/c4387a43b9dc6ee96e58cc516ece0603

Am I missing something?

**Comment by darkk** [comment]
Here are some regular queries regarding measurements that should be supported:
- confirmed cases of censorship, to show them in explorer
- unknown anomalies, to triage them and, possibly, extend methodology
- all anomalies (known and unknown), to give some estimates on anomalies while producing report (e.g. poor-man throttling detection)
- extra fields, to extend pipeline
- suppressed errors: bad rows during COPY, exceptions during row creation. Missing bucket is not metadb's deal, it may be alerted separately
- incomplete imports, some reports are truncated and only some of measurements are imported

Right now:
- there are 66.39M measurements in the DB: 1269 of 1324 buckets imported
- 2% of msm (1.35M) have recorded exceptions during processing
- 100% of measurements are technically _failed: true_ because of unprocessed fields like `probe_city`, `annotations` and so on. Top5 different residuals cover 68% of measurements, top15 -- 80%.

**Comment by darkk** [comment]
```sql
CREATE TABLE measurement (
...
    orig_sha1 sha1 NOT NULL,
    id uuid NOT NULL,
    input_no integer,
    exc integer[],
    residual_no integer NOT NULL,
    msm_failure boolean NULL,
    anomaly boolean NULL,
    confirmed boolean NULL
);

CREATE TABLE label (
    msm_no integer NOT NULL,
    msm_failure boolean NULL,
    anomaly boolean NULL,
    confirmed boolean NULL    
);

failure = exc IS NOT NULL OR residual_no IS NOT NULL OR COALESCE(label.msm_failure, measurement.msm_failure, false)
anomaly = COALESCE(label.anomaly, measurement.anomaly, false)
confirmed = COALESCE(label.confirmed, measurement.confirmed, false)
```

`failure` is always true right now because of non-null `residual_no` (that is non-null for a reason, see previous comment).

`label` table is useful to store manual markup of measurements, if trusted human declares some measurement as anomaly, that's useful input that should be stored. It's stored in separate table to ease various updates. It's not content-dependent as pipeline tries hard to preserve `msm_no` during updates. This table should be backed up using content-based address instead of `msm_no`, e.g. `(textname, orig_sha1)`. It also allows something like _confirmed negative_ as `false` in `label` table may override `true` in `measurement` table.

I'm going to think about it a bit more and start implementing that scheme tomorrow evening when/if I reach place with stable Internet connection.

**Comment by hellais** [comment]
> I'm going to think about it a bit more and start implementing that scheme tomorrow evening when/if I reach place with stable Internet connection.

Yes this schema looks sane and it's already something I can use to start implementing something. Thanks!

**Comment by hellais** [comment]
@darkk I have some questions:


* What is `exc integer[]`?

* What is `residual_no`?

* Is there a reason you are defining keys in the other order compared to how they are defined on all the other tables? Example:

```
CREATE TABLE measurement (
    msm_no integer NOT NULL,
    report_no integer NOT NULL,
);
CREATE TABLE report (
    report_no integer NOT NULL,
    autoclaved_no integer NOT NULL,
);

CREATE TABLE autoclaved (
    autoclaved_no integer NOT NULL,
);
```

In the above examples the foreign key goes from child to parent, while here it goes from parent to child.

Update: scratch that I guess given that this is a one-to-one (am I right?) that is probably the preferred pattern.

Also some extra thoughts:

* We may want in the future to support reporting false positives and use the `label` table to store this information or maybe a table on the side of that

**Comment by hellais** [comment]
Took a first stab at implementing this in here:
https://github.com/TheTorProject/ooni-measurements/pull/31/commits/1b021ceda9da5267f92b4dafa3b27a059c8f469b
https://github.com/TheTorProject/ooni-measurements/pull/31/commits/7400252b3a1a454c674d28910a8d70330e24ad8a

Let me know if I missed something.

**Comment by darkk** [comment]
`exc integer[]` is array of backtrace hashcodes generated by [`exc_hash`](https://github.com/TheTorProject/ooni-pipeline/blob/cace129189216d66510f7fa921d6d8d80196ffc2/af/shovel/centrifugation.py#L625-L635), the purpose is to catch "most popular" errors without logging them explicitly.

`residual_no` is marker for "schema" of leftover JSON fields that were not touched during processing, schemas are tracked in `residual` table. It's not the best way to track them (fields are not normalized, only values are scrubbed to represent their types), but that's useful as a start.

> Update: scratch that

Yep. I've not even understood your question, sorry :-) BTW, there are no explicit foreign keys, they were too slow during batch imports. I consider adding something like ooni_fsck() PL/pgSQL  function to have cross-table constraints explicitly defined. Tell me if you know better pattern.

> We may want in the future to support reporting false positives and use the label table to store this information or maybe a table on the side of that

That's **exactly** it's purpose :)

**Comment by hellais** [comment]
I would say that by some definition of done this is done.

I say @FedericoCeratto you should take a read through this to see if there is any useful information and once you have done so close this.

**Comment by hellais** [comment]
I am closing this issue.
